### ISSUE TITLE
Can't access weight from google drive

### ISSUE THREAD

**Issue by FriedaSmith** [meiguiz/SG-Grasp#1]
I can't access [weight](https://drive.google.com/file/d/1Ik9ffzRdolUc0g89fnDy8EQT9YG1Xx_d/view?usp=sharing) from google drive. it says "You need access"

![need_access](https://github.com/meiguiz/SG-Grasp/assets/64420430/aac64ca6-6b3a-484f-8e5d-0e90197a2501)

**Comment by meiguiz** [comment]
you can try again

**Comment by FriedaSmith** [comment]
Thanks
